@@ -215,7 +215,7 @@ kramdown:



# Sass/SCSS



sass:



  sass_dir: _sass



  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style



  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style











# Outputting


@@ -272,7 +272,7 @@ tag_archive:











# HTML Compression



# - http://jch.penibelst.de/



# - https://jch.penibelst.de/



compress_html:



  clippings: all



  ignore:

